### ISSUE TITLE
Scheme count broken with Xcode 10.1 for xctestrun file

### ISSUE THREAD

**Issue by MartyCatawiki** [fastlane/fastlane-plugin-firebase_test_lab#54]
With Xcode 10.1 i'm getting the error: `The app bundle may contain only one scheme, 2 found`
I only build for one scheme.

This error is due to to the extra key added since Xcode 10.1 named `__xctestrun_metadata__` in the `xctestrun` file.

See line:
https://github.com/fastlane/fastlane-plugin-firebase_test_lab/blob/4fa5d0c00eb1e51eda8036b93575e031696b576d/lib/fastlane/plugin/firebase_test_lab/helper/ios_validator.rb#L18

**Comment by janpio** [comment]
Any idea how to best fix this in the code? Maybe try to strip `__xctestrun_metadata__` before reading the size?

**Comment by MartyCatawiki** [comment]
I think you don't need to check the size. A few lines lower it will check the first one already `_, scheme_conf = conf.first`?

**Comment by MartyCatawiki** [comment]
@powerivq This issue is resolved by #55, can you please make a new release 1.0.1 of this plugin?

**Comment by powerivq** [comment]
@MartyCatawiki It was released yesterday. You can check it out.

**Comment by MartyCatawiki** [comment]
@powerivq Thanks it works now! I have one small remark

**Comment by johnrogers** [comment]
I still get this issue running 1.0.1.
