### ISSUE TITLE
Need the output from the Firebase command (bucket url)

### ISSUE THREAD

**Issue by nancy-gomez** [fastlane/fastlane-plugin-firebase_test_lab#60]
Your plugin does not output the actual link to where the test results are being stored in the google cloud bucket, this is vital for downloading results. Can you adjust the output so it still displays that instead of consuming the output?

**Comment by nancy-gomez** [comment]
Created a pull request for this issue, can you please check and verify everything looks good? I'd love to use this tool and need such a small change for my use case! https://github.com/fastlane/fastlane-plugin-firebase_test_lab/pull/61

**Comment by nancy-gomez** [comment]
I believe we are just missing the tag on the commit to make the release official? :) And then this can be closed off?

**Comment by powerivq** [comment]
I will cut a release and close this.
